### ISSUE TITLE
Please add:

### ISSUE THREAD

**Issue by sagupast** [zoomhub/zoomhub#107] opened 2015-02-26 05:35 UTC
http://zoom.it/gGwh
http://zoom.it/Hewf 
http://zoom.it/H0Tg
http://zoom.it/CGCi
http://zoom.it/hdR9
http://zoom.it/nGe6
http://zoom.it/VCbI
http://zoom.it/GrhI

THANK YOU!!!!

**Comment by iangilman** [comment] 2015-02-26 17:01
Thanks for the report, and for adding it to #89. Closing this as a duplicate of that.

**Closed by iangilman** 2015-02-26 17:01 UTC
