### ISSUE TITLE
Still queued... :-( :-( :-(

### ISSUE THREAD

**Issue by sagupast** [zoomhub/zoomhub#110] opened 2015-03-31 18:40 UTC
On Feb 24, 2015, at 4:57 PM, Chris Lewis <crlewis@gmail.com> wrote:

Sorry to see the end of Zoom it, but it's great news that the project is being taken over.
I have a number of queued images, it would be great if they could be reinstated, here's the list:
http://zoom.it/qr6d#full
http://zoom.it/yrZq#full
http://zoom.it/lxww#full
http://zoom.it/DHd#full
http://zoom.it/Qcv7#full
http://zoom.it/az2P#full
http://zoom.it/WtEy#full
http://zoom.it/NgiE#full
http://zoom.it/ku55#full
http://zoom.it/CMTh#full
http://zoom.it/At7E#full

Still queued but ask since many weeks... :-(

**Comment by iangilman** [comment] 2015-04-01 16:15
Yes, I'm sorry it's taking so long! Turns out we've run into a number of technical challenges, and everyone who is working on it are often busy with their day jobs. 

Anyway, keep reminding us. We definitely want to get it done! 

That said, I'm closing this as a duplicate of #108...we have this information there.

**Closed by iangilman** 2015-04-01 16:15 UTC
